export type ArticleBlock =
  | { type: 'p'; text: string }
  | { type: 'h'; text: string }
  | { type: 'quote'; text: string }
  | { type: 'list'; items: string[] }
  | { type: 'stats'; stats: ArticleStat[] }
  | { type: 'code'; code: string; lang?: string; caption?: string; href?: string; hrefLabel?: string }
  /** A chart rendered by tokenops (`tokenops fmt analyze --svg` / `spend --svg`), embedded verbatim. cmd is the exact command that produced it. */
  | { type: 'svg'; id: 'composition' | 'reads' | 'ratio' | 'fmt-roi'; cmd: string; caption?: string };

export interface ArticleStat {
  value: string;
  label: string;
}

export interface ArticleCta {
  heading: string;
  body: string;
  href: string;
  label: string;
}

export interface Article {
  slug: string;
  title: string;
  dek: string;
  date: string; // ISO
  readingMinutes: number;
  author: string;
  accent: string;
  tags: string[];
  blocks: ArticleBlock[];
  cta?: ArticleCta;
}

/**
 * Klarlabs writing — engineering notes.
 */
export const articles: Article[] = [
  {
    slug: 'where-ai-coding-tokens-actually-go',
    title: '800 to 1',
    dek: 'We set out to cut the token bill on our AI-assisted coding. The popular fix — make the model talk in terse shorthand — turned out to touch about 1% of it. Here is what the numbers actually showed, and the tool we built and open-sourced to find out.',
    date: '2026-07-03',
    readingMinutes: 9,
    author: 'Felix Geelhaar',
    accent: '#6366F1',
    tags: ['AI', 'Developer Tools', 'Measurement', 'Open Source'],
    blocks: [
      {
        type: 'p',
        text: 'Most of our development now runs through an AI coding agent. On a flat-rate subscription the dollar cost is fixed, but tokens are not free — they are rate-limit headroom. Burn through them and you hit a mid-task cutoff four hours into a refactor. So we wanted to spend fewer tokens per unit of work.',
      },
      {
        type: 'p',
        text: 'The advice that circulates is simple: tell the model to answer tersely — drop the filler, speak in fragments — and you cut your token usage by "up to 75%." It is a satisfying idea. We decided to measure whether it was true for us before believing it.',
      },
      {
        type: 'stats',
        stats: [
          { value: '~800 : 1', label: 'input tokens vs. output tokens, on our real usage' },
          { value: '0.12%', label: 'of our tokens are the model’s own prose' },
          { value: '$19k', label: 'API-list-price value absorbed by a flat plan (so $0 out of pocket)' },
        ],
      },
      {
        type: 'h',
        text: 'Output is a rounding error',
      },
      {
        type: 'p',
        text: 'Over roughly six months of real usage we sent tens of billions of input tokens and received about forty million output tokens back. That is a ratio near 800 to 1. Every turn re-sends the entire growing context — system prompt, tool definitions, file contents, command output, conversation history — to get back a few hundred tokens of reply.',
      },
      {
        type: 'svg',
        id: 'ratio',
        cmd: 'tokenops spend --svg ratio.svg',
        caption: 'From `tokenops spend`. The output bar is 0.12% of the total, drawn to scale — a hairline. That sliver is the only thing “make the AI talk terse” can touch.',
      },
      {
        type: 'p',
        text: 'The terse-talking trick compresses only the model’s prose, and it leaves code, tool calls, and structured output alone. That prose is 0.12% of our token volume. Even weighting for the fact that output tokens are priced several times higher than input, the absolute ceiling on what "make the AI talk less" could ever save us is around 1% of the bill. We were about to optimize a rounding error.',
      },
      {
        type: 'quote',
        text: 'The token-saving trick that goes viral optimizes the thing you can see — the model’s words — not the thing you can’t: the context you re-send every single turn.',
      },
      {
        type: 'h',
        text: 'Where the tokens actually live',
      },
      {
        type: 'p',
        text: 'So we pointed the analyzer at the logs the agent already writes and measured the composition of everything that flows into context. It was not the model’s prose. It was not even close.',
      },
      {
        type: 'svg',
        id: 'composition',
        cmd: 'tokenops fmt analyze --svg ./charts   # → composition.svg',
        caption: 'Generated by tokenops from our own logs (`tokenops fmt analyze --svg`). “Model prose” — the slice the terse-speak trick compresses — is third, and small.',
      },
      {
        type: 'p',
        text: 'We did not eyeball this, and we did not draw that chart by hand — tokenops rendered it. The tool reads the JSONL logs the agent already writes and reports the split directly, no daemon, no setup:',
      },
      {
        type: 'code',
        lang: 'console',
        code: `$ tokenops fmt analyze --top 6

Context composition — 768 sessions, 78539 tool results
  SOURCE                 ~TOKENS    SHARE
  Read                     14.3M    46.5%
  Bash                      8.2M    26.6%
  (assistant prose)         3.5M    11.4%
  (user prose)              1.1M     3.7%
  Agent                     861k     2.8%
  Edit                      723k     2.3%`,
        caption: 'tokenops fmt analyze — context composition from your own logs.',
        href: 'https://github.com/klarlabs-studio/tokenops',
        hrefLabel: 'github.com/klarlabs-studio/tokenops',
      },
      {
        type: 'h',
        text: 'Command output: real, but not where we assumed',
      },
      {
        type: 'p',
        text: 'Command output looked promising, so we built a deterministic compressor for it — 46 per-command formatters that strip the noise from tool output (progress bars, up-to-date chatter, passing-test scaffolding) while guaranteeing that no error, failure, or changed-state line is ever dropped. On a benchmark corpus it removes 57–68% of the volume.',
      },
      {
        type: 'p',
        text: 'Then we ran it against our actual command history — and it reclaimed 1–4%. The formatters are excellent at compressing noisy builds and verbose test runs. Our commands, it turned out, are mostly grep, cat, echo, and small git calls — already terse, nothing to strip. The catalog was not wrong; our usage simply does not lean on the commands it shines at. Honest measurement beat the demo number.',
      },
      {
        type: 'svg',
        id: 'fmt-roi',
        cmd: 'tokenops fmt analyze --svg ./charts   # → fmt-roi.svg',
        caption: 'From `tokenops fmt analyze`. The same 57–68% formatters, measured against our real command mix instead of a benchmark corpus.',
      },
      {
        type: 'h',
        text: 'The real lever: reading the same file twice',
      },
      {
        type: 'p',
        text: 'The biggest slice was file reads. Within it we looked for waste: the same file read more than once, and byte-identical content re-sent. About 16% of reads were repeats and 24% was duplicate content — reclaimable in principle. But more than half of all our reads already used ranged reads (offset/limit), and when we isolated the genuinely wasteful case — the same file read in full, unchanged, twice in a session — it came out to a handful of reads and a few thousand tokens across several sessions.',
      },
      {
        type: 'svg',
        id: 'reads',
        cmd: 'tokenops fmt analyze --svg ./charts   # → reads.svg',
        caption: 'Also from tokenops. Most repeats are ranged or post-edit — legitimate. A hook classifies each re-read live and reclaims only the genuinely wasteful case:',
      },
      {
        type: 'code',
        lang: 'console',
        code: `$ tokenops read-guard stats

read-guard — 112 reads seen across 3 sessions
  repeat reads (same file again in a session): 53
    ├─ reclaimable (unchanged full re-read): 4 · ~5354 tokens
    ├─ post-edit (file changed — not waste):  2
    └─ ranged (intentional partial re-read):  47`,
        caption: 'tokenops read-guard — a Claude Code hook that blocks only redundant re-reads.',
        href: 'https://github.com/klarlabs-studio/tokenops',
        hrefLabel: 'github.com/klarlabs-studio/tokenops',
      },
      {
        type: 'p',
        text: 'In other words: we were already reading efficiently. The lever existed, but for us it was nearly empty. The tool proved that rather than assuming it.',
      },
      {
        type: 'quote',
        text: 'The biggest win was not a compression trick. It was measuring — which killed three plausible optimizations before we shipped snake oil to ourselves.',
      },
      {
        type: 'h',
        text: 'What we shipped',
      },
      {
        type: 'p',
        text: 'The through-line of all of this is the same: you cannot optimize what you have not measured, and the AI-token economy is full of confident advice measured against the wrong denominator. So the useful artifact was never a single compression knob — it was the measurement itself.',
      },
      {
        type: 'p',
        text: 'We built and open-sourced tokenops: a local-first CLI and MCP server. It reads the logs your agent already writes and tells you where your tokens actually go — no daemon, no account, no telemetry leaving your machine. It ships the deterministic command-output formatters, and a hook that reclaims genuinely redundant file re-reads at the source. Every number and chart in this post came out of it, pointed at our own usage.',
      },
      {
        type: 'code',
        lang: 'console',
        code: `$ brew install felixgeelhaar/tap/tokenops

# where do my AI-coding tokens actually go?
$ tokenops fmt analyze

# what would the command-output formatters save on my traffic?
$ tokenops fmt learn`,
        caption: 'Point it at your own logs. Local-first, deterministic, no telemetry.',
        href: 'https://github.com/klarlabs-studio/tokenops',
        hrefLabel: 'github.com/klarlabs-studio/tokenops',
      },
      {
        type: 'h',
        text: 'Point it at your own usage',
      },
      {
        type: 'p',
        text: 'Setup is not installing another optimizer — it is aiming the measurement at your own situation. Everything below reads the logs your agent already writes; the only question is how much you want wired in. Four common starting points, in order of commitment.',
      },
      {
        type: 'p',
        text: 'If you only want to check your own denominator before trusting anyone’s percentage: install, run one command, read the split. No daemon, no account, nothing left running. This is where every number in this post came from.',
      },
      {
        type: 'code',
        lang: 'console',
        code: `$ brew install felixgeelhaar/tap/tokenops

# context composition from the logs already on disk — no daemon, no account
$ tokenops fmt analyze`,
        caption: 'Cost-curious / skeptic — measure first, decide later. Nothing persists.',
        href: 'https://github.com/klarlabs-studio/tokenops',
        hrefLabel: 'github.com/klarlabs-studio/tokenops',
      },
      {
        type: 'p',
        text: 'If you are the person in this post — coding all day against a Claude Max or ChatGPT plan and tired of mid-task cutoffs — bind your plan so tokenops can predict the window, and wire the read-guard hook so genuinely redundant full re-reads never spend tokens. It starts in observe mode; you flip it to active once you have seen what it would block.',
      },
      {
        type: 'code',
        lang: 'console',
        code: `$ tokenops init --detect                      # sniff installed AI clients
$ tokenops plan set anthropic claude-max-20x  # predict the rate-limit window
$ tokenops read-guard hook                    # prints the Claude Code settings.json block`,
        caption: 'Solo dev on a flat-rate plan — predict the cutoff, reclaim redundant re-reads.',
      },
      {
        type: 'p',
        text: 'If you are building your own agent or MCP workflow, the deterministic formatters are the reusable part. Wrap a noisy command so its output is compressed — losslessly for errors and changed state — before it ever reaches context, or run the whole thing as an MCP server your agent calls directly.',
      },
      {
        type: 'code',
        lang: 'console',
        code: `$ tokenops fmt -- go test ./...            # compress this command's output in place
$ eval "$(tokenops fmt hook --shell zsh)"  # then: export TOKENOPS_FMT=1 to activate
$ tokenops serve                           # MCP server over stdio — tools your agent calls`,
        caption: 'Agent / tool builder — the deterministic formatters and MCP tools, in your own pipeline.',
      },
      {
        type: 'p',
        text: 'And if you run a team, the daemon adds per-project and per-session attribution: which project burns the most, and where a specific session went wide. The coach turns that into ranked, dollar- and hour-denominated recommendations — measured against your traffic, not a benchmark corpus.',
      },
      {
        type: 'code',
        lang: 'console',
        code: `$ tokenops start            # daemon: proxy + analytics + dashboard
$ tokenops spend --by agent  # which project burns the most
$ tokenops coach prompts     # per-session waste, ranked by tokens / $ / hours`,
        caption: 'Team / eng lead — attribution across projects and sessions, plus ranked coaching.',
      },
      {
        type: 'h',
        text: 'The lesson',
      },
      {
        type: 'p',
        text: 'For us the honest answer was: you are already lean, and the fashionable optimizations would have bought almost nothing. That is not a disappointing result — it is the correct one, and a tool that can prove it is worth more than one that manufactures a saving. Measure your own usage. The denominator is almost never where the internet says it is.',
      },
    ],
    cta: {
      heading: 'tokenops is open source',
      body: 'Point it at your own logs and see where your AI-coding tokens actually go. Local-first, deterministic, no telemetry.',
      href: 'https://github.com/klarlabs-studio/tokenops',
      label: 'View on GitHub',
    },
  },
];
